# Generated by Django 2.0.5 on 2018-05-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180525_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_create_update_or_delete_author', 'Create, update or delete author details'),)},
        ),
    ]
